use corre_core::config::*;
use std::collections::HashMap;
use std::path::PathBuf;

use super::state::SetupState;

/// Returns the OS-appropriate default data directory as a tilde-prefixed string for config files.
pub fn default_data_dir() -> String {
    if cfg!(target_os = "macos") {
        "~/Library/Application Support/corre".into()
    } else if cfg!(target_os = "windows") {
        "~/AppData/Local/corre".into()
    } else {
        "~/.local/share/corre".into()
    }
}

/// Returns the OS-appropriate resolved data directory path.
pub fn resolved_data_dir() -> PathBuf {
    if cfg!(target_os = "macos") {
        dirs::home_dir().unwrap_or_else(|| PathBuf::from(".")).join("Library/Application Support/corre")
    } else if cfg!(target_os = "windows") {
        dirs::data_local_dir().unwrap_or_else(|| dirs::home_dir().unwrap_or_else(|| PathBuf::from(".")).join("AppData/Local")).join("corre")
    } else {
        dirs::home_dir().unwrap_or_else(|| PathBuf::from(".")).join(".local/share/corre")
    }
}

/// Returns the OS-appropriate command name for npx.
fn npx_command() -> &'static str {
    if cfg!(target_os = "windows") { "npx.cmd" } else { "npx" }
}

/// Build a `CorreConfig` from the wizard state, ready for TOML serialization.
pub fn build_config(state: &SetupState) -> CorreConfig {
    let mut mcp_servers = HashMap::new();

    // Always include brave-search if daily-brief is enabled
    if state.enabled_capabilities.iter().any(|c| c == "daily-brief") {
        mcp_servers.insert(
            "brave-search".into(),
            McpServerConfig {
                command: npx_command().into(),
                args: vec!["-y".into(), "@brave/brave-search-mcp-server".into()],
                env: {
                    let mut env = HashMap::new();
                    env.insert("BRAVE_API_KEY".into(), state.brave_api_key_env.clone().unwrap_or_else(|| "BRAVE_API_KEY".into()));
                    env
                },
            },
        );
    }

    let hour = state.schedule_hour.unwrap_or(5);
    let port = state.news_port.unwrap_or(3200);

    let capabilities: Vec<CapabilityConfig> = state
        .enabled_capabilities
        .iter()
        .map(|name| match name.as_str() {
            "daily-brief" => CapabilityConfig {
                name: "daily-brief".into(),
                description: "Researches topics and produces a daily news briefing".into(),
                schedule: format!("0 0 {hour} * * *"),
                mcp_servers: vec!["brave-search".into()],
                config_path: Some("config/topics.md".into()),
                enabled: true,
            },
            other => CapabilityConfig {
                name: other.into(),
                description: String::new(),
                schedule: format!("0 0 {hour} * * *"),
                mcp_servers: Vec::new(),
                config_path: None,
                enabled: true,
            },
        })
        .collect();

    CorreConfig {
        general: GeneralConfig { data_dir: default_data_dir(), log_level: "info".into() },
        llm: LlmConfig {
            provider: "openai-compatible".into(),
            base_url: state.llm_base_url.clone().unwrap_or_else(|| "https://api.venice.ai/api/v1".into()),
            model: state.llm_model.clone().unwrap_or_else(|| "zai-org-glm-4.7-flash".into()),
            api_key_env: state.llm_api_key_env.clone().unwrap_or_else(|| "VENICE_API_KEY".into()),
            temperature: 0.3,
            max_tokens: 4096,
            max_concurrent: 10,
        },
        news: NewsConfig {
            bind: format!("127.0.0.1:{port}"),
            title: state.news_title.clone().unwrap_or_else(|| "Corre News".into()),
            editor_token: None,
        },
        mcp: McpConfig { servers: mcp_servers },
        capabilities,
        safety: SafetyConfig::default(),
    }
}

/// Default topics.md content for new users.
pub const DEFAULT_TOPICS: &str = "\
# Daily Brief Topics

## Technology
Find the latest developments in technology, programming, and software engineering.

## World News
The latest important developments in world news and geopolitics.

## Science
Interesting scientific discoveries, research papers, and breakthroughs.
";

/// Format a `CorreConfig` as a TOML string with helpful comments.
pub fn format_config_toml(config: &CorreConfig) -> anyhow::Result<String> {
    // Use toml serialization, then add comments
    let raw = toml::to_string_pretty(config)?;

    // Add a header comment
    let data_dir = default_data_dir();
    let header = format!(
        "\
# Corre configuration — generated by `corre setup`
# Edit this file to change your LLM provider, topics, schedules, etc.
# API keys are stored in {data_dir}/.env (not in this file)

"
    );
    Ok(format!("{header}{raw}"))
}
