worker_processes 1;

events {
    worker_connections 128;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    server {
        listen 5580;
        server_name _;

        location /mcp/ {
            alias /usr/share/nginx/html/mcp/;
            autoindex off;

            # registry manifest
            location ~* \.json$ {
                add_header Content-Type application/json;
            }
        }

        location = /health {
            return 200 'ok';
            add_header Content-Type text/plain;
        }
    }
}
