#!/usr/bin/env bash
set -euo pipefail

# ── Constants ────────────────────────────────────────────────────────────────

CORRE_REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BINARY_PATH="${BINARY_PATH:-${CORRE_REPO_DIR}/target/release/corre}"
CORRE_DATA_DIR="${HOME}/.local/share/corre"
CORRE_ENV_FILE="${CORRE_DATA_DIR}/.env"
CORRE_CONFIG="${CORRE_REPO_DIR}/corre.toml"
CORRE_SERVICE="corre"

# Track what was done for the summary
DID_SYSTEMD=false
DID_TAILSCALE=false
TAILSCALE_IP=""

# ── Color helpers ────────────────────────────────────────────────────────────

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m'

info()  { echo -e "${BLUE}[INFO]${NC}  $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }
ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }

ask() {
    echo -en "${BOLD}$*${NC} "
}

# ── Error trap ───────────────────────────────────────────────────────────────

trap_err() {
    error "Script failed at line $1. Check output above for details."
    exit 1
}
trap 'trap_err ${LINENO}' ERR

# ── Helpers ──────────────────────────────────────────────────────────────────

confirm() {
    local prompt="$1"
    local reply
    ask "${prompt} [y/N]"
    read -r reply
    [[ "${reply}" =~ ^[Yy]$ ]]
}

command_exists() {
    command -v "$1" &>/dev/null
}

pkg_installed() {
    dpkg -s "$1" &>/dev/null 2>&1
}

# ── install_system_deps ─────────────────────────────────────────────────────

install_system_deps() {
    info "Checking system dependencies..."

    local to_install=()

    for pkg in curl nodejs npm; do
        if ! pkg_installed "${pkg}"; then
            to_install+=("${pkg}")
        fi
    done

    if [[ ${#to_install[@]} -gt 0 ]]; then
        info "Installing: ${to_install[*]}"
        sudo apt-get update -qq
        sudo apt-get install -y -qq "${to_install[@]}"
    else
        ok "System packages already installed (curl, nodejs, npm)"
    fi

    # Validate Node.js version
    if command_exists node; then
        local node_major
        node_major="$(node --version | sed 's/^v//' | cut -d. -f1)"
        if [[ "${node_major}" -lt 18 ]]; then
            warn "Node.js version $(node --version) is below 18."
            warn "Consider installing a newer version via https://deb.nodesource.com/"
        else
            ok "Node.js $(node --version) meets the >= 18 requirement"
        fi
    fi
}

# ── verify_mcp_servers ──────────────────────────────────────────────────────

verify_mcp_servers() {
    info "Verifying MCP server availability..."

    if command_exists npx; then
        ok "npx available (used for brave-search MCP server)"
    else
        warn "npx not found — brave-search MCP server will not work"
    fi
}

# ── setup_env_file ──────────────────────────────────────────────────────────

setup_env_file() {
    info "Setting up environment file..."

    mkdir -p "${CORRE_DATA_DIR}"

    if [[ -f "${CORRE_ENV_FILE}" ]]; then
        warn "Environment file already exists at ${CORRE_ENV_FILE}"
        if ! confirm "Overwrite it?"; then
            info "Keeping existing .env file"
            return 0
        fi
    fi

    echo ""
    info "Enter your API keys (input is hidden)."
    info "Press Enter to skip a key if you don't have it yet."
    echo ""

    ask "VENICE_API_KEY:"
    read -rs venice_key
    echo ""

    ask "BRAVE_API_KEY:"
    read -rs brave_key
    echo ""

    {
        echo "# Corre API keys — generated by deploy.sh"
        [[ -n "${venice_key}" ]] && echo "VENICE_API_KEY=${venice_key}"
        [[ -n "${brave_key}" ]]  && echo "BRAVE_API_KEY=${brave_key}"
    } > "${CORRE_ENV_FILE}"

    chmod 600 "${CORRE_ENV_FILE}"
    ok "Environment file written to ${CORRE_ENV_FILE} (mode 600)"
}

# ── setup_systemd ───────────────────────────────────────────────────────────

setup_systemd() {
    echo ""
    if ! confirm "Set up systemd service for Corre?"; then
        info "Skipping systemd setup"
        return 0
    fi

    local current_user
    current_user="$(whoami)"
    local service_file="/etc/systemd/system/${CORRE_SERVICE}.service"

    # Check if already running
    if systemctl is-active --quiet "${CORRE_SERVICE}" 2>/dev/null; then
        warn "Corre service is already running."
        if ! confirm "Restart it with the new configuration?"; then
            info "Leaving existing service untouched"
            return 0
        fi
    fi

    info "Writing systemd unit to ${service_file}..."

    sudo tee "${service_file}" > /dev/null <<EOF
[Unit]
Description=Corre — personal AI task scheduler and newspaper
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=${current_user}
WorkingDirectory=${CORRE_REPO_DIR}
EnvironmentFile=${CORRE_ENV_FILE}
Environment=PATH=${HOME}/.cargo/bin:/usr/local/bin:/usr/bin:/bin
ExecStart=${BINARY_PATH} run
Restart=on-failure
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF

    sudo systemctl daemon-reload
    sudo systemctl enable "${CORRE_SERVICE}"
    sudo systemctl restart "${CORRE_SERVICE}"

    # Give it a moment to start
    sleep 2

    if systemctl is-active --quiet "${CORRE_SERVICE}"; then
        ok "Corre service is running"
    else
        warn "Service may not have started cleanly. Check: journalctl -u ${CORRE_SERVICE} -e"
    fi

    DID_SYSTEMD=true
}

# ── setup_tailscale ─────────────────────────────────────────────────────────

setup_tailscale() {
    echo ""
    if ! confirm "Set up Tailscale for remote access?"; then
        info "Skipping Tailscale setup"
        return 0
    fi

    if ! command_exists tailscale; then
        info "Installing Tailscale..."
        curl -fsSL https://tailscale.com/install.sh | sh
    else
        ok "Tailscale already installed"
    fi

    ask "Headscale coordination server URL (leave blank for default Tailscale):"
    local headscale_url
    read -r headscale_url

    if [[ -n "${headscale_url}" ]]; then
        info "Connecting to Headscale at ${headscale_url}..."
        sudo tailscale up --login-server="${headscale_url}"
    else
        info "Connecting to Tailscale..."
        sudo tailscale up
    fi

    TAILSCALE_IP="$(tailscale ip -4 2>/dev/null || echo "")"

    if [[ -n "${TAILSCALE_IP}" ]]; then
        ok "Tailscale connected. IP: ${TAILSCALE_IP}"

        echo ""
        if confirm "Update corre.toml bind address from 127.0.0.1:5510 to 0.0.0.0:5510?"; then
            if grep -q 'bind = "127.0.0.1:5510"' "${CORRE_CONFIG}"; then
                sed -i 's/bind = "127.0.0.1:5510"/bind = "0.0.0.0:5510"/' "${CORRE_CONFIG}"
                ok "Updated bind address to 0.0.0.0:5510"
            else
                warn "Could not find expected bind line in ${CORRE_CONFIG}. Edit manually if needed."
            fi
        fi
    else
        warn "Could not determine Tailscale IP. Check: tailscale status"
    fi

    DID_TAILSCALE=true
}

# ── setup_tor_placeholder ───────────────────────────────────────────────────

setup_tor_placeholder() {
    echo ""
    info "Tor hidden service setup is not yet implemented."
    info "Future plan: install tor, configure hidden service on port 5510, display .onion address."
    # TODO:
    # - sudo apt-get install tor
    # - Configure /etc/tor/torrc with HiddenServiceDir and HiddenServicePort
    # - sudo systemctl restart tor
    # - Read .onion address from HiddenServiceDir/hostname
}

# ── print_summary ───────────────────────────────────────────────────────────

print_summary() {
    echo ""
    echo -e "${BOLD}════════════════════════════════════════════════════════${NC}"
    echo -e "${BOLD}  Corre Deployment Summary${NC}"
    echo -e "${BOLD}════════════════════════════════════════════════════════${NC}"
    echo ""
    echo -e "  Binary:        ${BINARY_PATH}"
    echo -e "  Config:        ${CORRE_CONFIG}"
    echo -e "  Data dir:      ${CORRE_DATA_DIR}"
    echo -e "  Env file:      ${CORRE_ENV_FILE}"
    echo ""

    if [[ "${DID_SYSTEMD}" == true ]]; then
        local status
        status="$(systemctl is-active "${CORRE_SERVICE}" 2>/dev/null || echo "unknown")"
        echo -e "  Service:       ${CORRE_SERVICE} (${status})"
        echo -e "  Logs:          journalctl -u ${CORRE_SERVICE} -f"
    else
        echo -e "  Service:       not configured (run manually with: ${BINARY_PATH} run)"
    fi

    if [[ "${DID_TAILSCALE}" == true && -n "${TAILSCALE_IP}" ]]; then
        echo -e "  Tailscale IP:  ${TAILSCALE_IP}"
        echo -e "  Remote URL:    http://${TAILSCALE_IP}:5510"
    fi

    echo ""
    echo -e "  Local URL:     http://127.0.0.1:5510"
    echo ""
    echo -e "${BOLD}════════════════════════════════════════════════════════${NC}"
}

# ── main ────────────────────────────────────────────────────────────────────

main() {
    echo ""
    echo -e "${BOLD}Corre Deploy${NC}"
    echo -e "Repository: ${CORRE_REPO_DIR}"
    echo ""

    # Validate binary exists
    if [[ ! -x "${BINARY_PATH}" ]]; then
        error "Binary not found at ${BINARY_PATH}"
        error "Build it first with: cargo build --release"
        error "Or set BINARY_PATH to point at an existing binary."
        exit 1
    fi
    ok "Binary found at ${BINARY_PATH}"

    # Validate config exists
    if [[ ! -f "${CORRE_CONFIG}" ]]; then
        error "Config not found at ${CORRE_CONFIG}"
        exit 1
    fi
    ok "Config found at ${CORRE_CONFIG}"

    install_system_deps
    verify_mcp_servers
    setup_env_file
    setup_systemd
    setup_tailscale
    setup_tor_placeholder
    print_summary
}

main "$@"
